{% set name = "jupyterlab_nbconvert_nocode" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7c1617d2b49d425984d30e5e0cc9e7e1b354bb570dab474cafffb70f61b5162

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging
  run:
    - python >=3.6
    - jupyterlab >=1.0.0
    - nbconvert >=6.0.0

test:
  imports:
    - jupyterlab_nbconvert_nocode
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: jupyterlab_nbconvert_nocode
    build:
      noarch: python
  - name: jupyterlab-nbconvert-nocode
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage("jupyterlab_nbconvert_nocode", exact=True) }}

about:
  home: https://github.com/timkpaine/jupyterlab_nbconvert_nocode
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A simple helper library with 2 NBConvert exporters for PDF/HTML export with no code cells
  dev_url: https://github.com/timkpaine/jupyterlab_nbconvert_nocode

extra:
  recipe-maintainers:
    - timkpaine
