{% set name = "jupyterlab_nbconvert_nocode" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 656e0431aeef9266c8973c55124ace6f7ce864f4432a029c1ab5978b81453589

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.3.1
  run:
    - python >={{ python_min }}
    - jupyterlab >=3.5
    - nbconvert >=6.0.0

test:
  imports:
    - jupyterlab_nbconvert_nocode
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

outputs:
  - name: jupyterlab_nbconvert_nocode
  - name: jupyterlab-nbconvert-nocode
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("jupyterlab_nbconvert_nocode", exact=True) }}

about:
  home: https://github.com/timkpaine/jupyterlab_nbconvert_nocode
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A simple helper library with 2 NBConvert exporters for PDF/HTML export with no code cells
  dev_url: https://github.com/timkpaine/jupyterlab_nbconvert_nocode

extra:
  recipe-maintainers:
    - timkpaine
